FROM node:8.11.4
RUN mkdir /usr/src/app
WORKDIR /usr/src/app
COPY package.json /usr/src/app/package.json
RUN npm install
RUN npm install -g @angular/cli@6.2.1
COPY . /usr/src/app
EXPOSE 4200
CMD ng serve --host 0.0.0.0
